Интерграционное тестирование
Viacheslav666/SpringBootStart pull request #7
Opened 2023-07-31 08:52 UTC by Viacheslav666

Просьба помочь, не пойму в чем может быть ошибка

2023-07-31 11:12 UTC, isavinov requested changes

2023-07-31 11:12 UTC, isavinov commented on pom.xml
> +            <groupId>org.mockito</groupId>
Не нужно подключать мокито, он уже идет в составе 
spring-boot-starter-test

2023-07-31 11:12 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/weblibrary1/service/IntegrationTest/employeeIntegationTest.java
> +public class employeeIntegationTest {
Названия классов с большой буквы

2023-07-31 11:12 UTC, isavinov commented on src/main/java/ru/skypro/lessons/springboot/weblibrary1/controller/EmployeeController.java
в контроллере нет нужного конструктора, спринг не может заинжектить сервис

2023-07-31 11:12 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/weblibrary1/service/IntegrationTest/employeeIntegationTest.java
> +        mockMvc.perform(get("/employees")
position это параметр, он передается так
```
mockMvc.perform(get("/employees")
                        .param("position","Java"))
```

2023-07-31 11:12 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/weblibrary1/service/IntegrationTest/employeeIntegationTest.java
> +                new Employee(1, "Kirill", 20000, position2, new Report(1,"file")),
id сотрудников дублируются

2023-08-08 17:11 UTC, Viacheslav666 commented
Закончил интеграционное тестирование

2023-08-08 17:12 UTC, merged